config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #get '/meets'
  get '/users', to:'users#index'
  get '/doctor/new', to: 'doctors#new', as: :new_doctor
  get 'user', to: 'users#show'

  get '/users/sign_in', to: 'users#sign_in'
  post '/users/login', to: 'users#login', as: :login
  get '/users/logout', to: 'users#logout', as: :logout

  get '/users/sign_up', to: 'users#sign_up'
  post '/users/register', to: 'users#create', as: :register

  get '/meets/new', to: 'meets#new', as: :new_meet

  #get '/login', to: 'users#sign_in'
  #post '/login', to: 'users#sign_in'

  resources :users
  resources :doctors
  resources :meets
  # Defines the root path route ("/")
  root "doctors#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :meet

  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :date_of_birth, presence: true
  validates :specialty, presence: true
  validate :minimum_age_of_18

  def full_name
    "#{first_name} #{last_name}"
  end

  private

  def minimum_age_of_18
    return if date_of_birth.blank?

    if date_of_birth + 18.years > Date.current
      errors.add(:date_of_birth, "must be at least 18 years ago")
    end
  end
end

app/models/meet.rb
class Meet < ApplicationRecord
  belongs_to :doctor
  belongs_to :user

  validates :doctor_id, presence: true
  validates :user_id, presence: true
  validates :appointment_date_time, presence: true
  validate :appointment_uniqueness_for_doctor
  validate :appointment_must_be_in_future

  private

  def appointment_uniqueness_for_doctor
    return if doctor_id.blank? || appointment_date_time.blank?

    if Meet.exists?(doctor_id: doctor_id, appointment_date_time: appointment_date_time)
      errors.add(:appointment_date_time, "has already been scheduled for this doctor")
    end
  end

  def appointment_must_be_in_future
    return if appointment_date_time.blank?

    if appointment_date_time < Time.now
      errors.add(:appointment_date_time, "cannot be in the past")
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :meet
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness:true , on:create
  validates :birth_date, presence: true
  validate :minimum_age_of_18
  validate :valid_phone_number

  private

  def minimum_age_of_18
    return if birth_date.blank?

    if birth_date + 18.years > Date.current
      errors.add(:birth_date, "must be at least 18 years ago")
    end
  end

  def valid_phone_number
    return if phone.blank?

    unless Phonelib.valid_for_country?(phone, "UA")
      errors.add(:phone, "is invalid")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/doctors_controller.rb
# app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  def index
    @doctor = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor, notice: 'Doctor was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @doctor.update(doctor_params)
      redirect_to @doctor, notice: 'Doctor was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_url, notice: 'Doctor was successfully destroyed.'
  end

  private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:first_name, :last_name, :date_of_birth, :specialty)
  end
end

app/controllers/meets_controller.rb
# app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: [:show, :edit, :update, :destroy]

  def index
    @meets = Meet.includes(:user, :doctor).all
  end

  def show
  end

  def new
    @meet = Meet.new
    @doctor = Doctor.find(params[:doctor_id])
    @user = User.find(session[:user_id])
    @meet.doctor = @doctor
    @meet.user = @user
  end

  def create
    @meet = Meet.new(meet_params)
    if @meet.save
      redirect_to @meet, notice: 'Meet was successfully created.'
    end
  end

  def edit
  end

  def update
    if @meet.update(meet_params)
      redirect_to @meet, notice: 'Meet was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @meet.destroy
    redirect_to meets_url, notice: 'Meet was successfully destroyed.'
  end

  private

  def set_meet
    @meet = Meet.find(params[:id])
  end

  def meet_params
    params.require(:meet).permit(:user_id, :doctor_id, :appointment_date_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

   def index
    @user = User.new
   end

  def sign_up
    @user = User.new
  end

  def sign_in
    @user = User.new
  end

  def login
    user = User.find_by(email: params[:user][:email])
    if user&.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:alert] = "Invalid email or password"
      redirect_to login_path
    end
  end

  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  def create
    @user = User.new(user_params)
    if @user.save
    else
      flash[:alert] = "Помилка при реєстрації"
      redirect_to register_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :phone, :email, :password, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/sign_in_helper.rb
module SignInHelper
end

app/helpers/sign_up_helper.rb
module SignUpHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctors/_doctor.html.erb
<div id="<%= dom_id doctor %>">
  <div class="doc1">
    <h2 class="hdoc"><%= doctor.first_name %> <%= doctor.last_name %></h2>
    <p class="specialty"><%= doctor.specialty %></p>
    <%= link_to new_meet_path(doctor_id: doctor.id), class: "button1" do %>
      <% if session[:user_id] %>
        <h3 class="button1">Записатись до лікаря</h3>
      <% end %>
    <% end %>
  </div>
</div>

app/views/doctors/edit.html.erb
<!-- app/views/doctors/edit.html.erb -->
<h1>Edit Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/form.html.erb
<!-- app/views/doctors/_form.html.erb -->
<%= form_with(model: doctor, local: true) do |form| %>
  <% if doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
        <% doctor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :specialty %>
    <%= form.text_field :specialty %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/doctors/index.html.erb
<div class="wrapper">

  <div class="doctor-container">
    <% @doctor.each do |doctor| %>
      <%= render doctor %>
    <% end %>
  </div>

  <% if flash[:notice] %>
    <p style="color: green"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p style="color: red"><%= flash[:alert] %></p>
  <% end %>

</div>

app/views/doctors/new.html.erb
<!-- app/views/doctors/new.html.erb -->
<h1>New Doctor</h1>

<%= render 'form', doctor: @doctor %>

<%= link_to 'Back', doctors_path %>

app/views/doctors/show.html.erb
<!-- app/views/doctors/show.html.erb -->
<h1>Doctor</h1>

<p><strong>First Name:</strong> <%= @doctor.first_name %></p>
<p><strong>Last Name:</strong> <%= @doctor.last_name %></p>
<p><strong>Date of Birth:</strong> <%= @doctor.date_of_birth %></p>
<p><strong>Specialty:</strong> <%= @doctor.specialty %></p>

<br>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Appointment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "share/navbar"%>

    <%= yield %>
  </body>
</html>

app/views/meets/_form.html.erb
<!-- app/views/meets/_form.html.erb -->
<%= form_with(model: meet, local: true) do |form| %>


  <%= form.hidden_field :doctor_id, value: @doctor.id %>
  <%= form.hidden_field :user_id, value: @user.id %>

  <div class="field">
    <% if flash[:alert] %>
    <% end %>
    <h2 class="h2_meet"><%=meet.doctor.first_name %>
    <%=meet.doctor.last_name %></h2>
    <%=meet.doctor.specialty %>



    <h2 class="h2_meet"><%=meet.user.first_name %>
      <%=meet.user.last_name %></h2>



    <%= form.label :appointment_date_time %><br>
    <%= form.datetime_local_field :appointment_date_time, step:1800 %>



    <%= form.submit 'Записатись', class: 'button1' %>


  </div>



<% end %>

app/views/meets/edit.html.erb
<!-- app/views/meets/edit.html.erb -->
<h1>Edit Meet</h1>

<%= render 'form', meet: @meet %>

<%= link_to 'Back', meets_path %>

app/views/meets/form.html.erb
<!-- app/views/meets/_form.html.erb -->
<%= form_with(model: meet, local: true) do |form| %>
  <% if meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
        <% meet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :doctor_id %>
    <%= form.collection_select :doctor_id, Doctor.all, :id, :full_name %>
  </div>

  <div class="field">
    <%= form.label :appointment_date_time %>
    <%= form.datetime_field :appointment_date_time %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meets/new.html.erb
<!-- app/views/meets/new.html.erb -->
<h1>New Meet</h1>

<%= render 'form', meet: @meet %>

app/views/meets/show.html.erb
<!-- app/views/meets/show.html.erb -->
<h1>Meet</h1>

<p><strong>User:</strong> <%= @meet.user.first_name %> <%= @meet.user.last_name %></p>
<p><strong>Doctor:</strong> <%= @meet.doctor.first_name %> <%= @meet.doctor.last_name %></p>
<p><strong>Appointment Date/Time:</strong> <%= @meet.appointment_date_time %></p>

<br>

<%= link_to 'Edit', edit_meet_path(@meet) %> |
<%= link_to 'Back', meets_path %>

app/views/share/_navbar.html.erb
<header class="header">
  <div class="container">
    <div class="header_inner">
      <div class="header_logo"><a class="logo" href="/doctors" >dr.practice</a></div>

      <% if session[:user_id] %>
        <nav>
          <%= link_to "Вийти",  logout_path, method: :delete , class: 'nav_link' %>
        </nav>
      <% else %>
        <nav class="nav">
          <a class="nav_link" href="/users/sign_in">Увійти</a>
          <a class="nav_link" href="/users/sign_up">Реєстрація</a>
        </nav>
      <% end %>
    </div>
  </div>
</header>

app/views/users/_form_sign_in.html.erb
<div class="page">

  <main class="content">
    <div class="main">
      <div class="container1">

        <div class="container3">
          <h1 class="hh1">Вхід</h1>

          <% if flash[:notice] %>
            <p style="color: green"><%= flash[:notice] %></p>
          <% end %>

          <% if flash[:alert] %>
            <p style="color: red"><%= flash[:alert] %></p>
          <% end %>

          <%= form_with(model: @user, url: login_path) do |form| %>

            <div class="form-group">
              <!-- <input type="text", class='input1', placeholder="Email"> -->
              <%= form.email_field :email, placeholder: "Email" %>
            </div>

            <div class="form-group">
              <!--  <input type="password", class='input1', placeholder="Password"> -->
              <%= form.password_field :password, placeholder: "Password" %>
            </div>

            <div class="button_reg">
              <button type="submit" class="buttonr_reg">Увійти</button>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </main>



</div>

app/views/users/_form_sign_up.html.erb
<div class="page">

  <main class="content">
    <div class="main">
      <div class="container1">

        <div class="container3">

          <h1 class="hh1">Реєстрація користувача</h1>

          <%= form_with(model: @user, url: register_path) do |form| %>
            <div class="form-group">
              <%= form.label :last_name, 'Прізвище<i>*</i>'.html_safe %><br>
              <%= form.text_field :last_name, class: 'input1', placeholder: 'Бутко' %>
            </div>

            <div class="form-group">
              <%= form.label :first_name, "Ім'я<i>*</i>".html_safe %><br>
              <%= form.text_field :first_name, class: 'input1', placeholder: 'Михайло' %>
            </div>

            <div class="form-group">
              <%= form.label :birth_date, 'Дата народження<i>*</i>'.html_safe %><br>
              <%= form.date_field :birth_date, class: 'input1' %>
            </div>

            <div class="form-group">
              <%= form.label :password, 'Пароль<i>*</i>'.html_safe %><br>
              <%= form.password_field :password, class: 'input1', placeholder: 'Пароль' %>
            </div>

            <div class="form-group">
              <%= form.label :phone, 'Телефон<i>*</i>'.html_safe %><br>
              <%= form.text_field :phone, class: 'input1', placeholder: '+380660277353', inputmode: 'tel'  %>
            </div>


            <div class="form-group">
              <%= form.label :email, 'E-mail' %><br>
              <%= form.text_field :email, class: 'input1', placeholder: 'qwerty@gmail.com' %>
            </div>

            <div class="button_reg">
              <%= form.submit 'Реєстрація', class: 'buttonr_reg' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <% if flash[:notice] %>
      <p style="color: green"><%= flash[:notice] %></p>
    <% end %>

    <% if flash[:alert] %>
      <p style="color: red"><%= flash[:alert] %></p>
    <% end %>

  </main>
</div>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<h1>Edit User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/form.html.erb
<!-- app/views/users/_form.html.erb -->
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.number_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/login.html.erb
<main class="content">
  <div class="main">
    <div class="container1">

      <div class="container3">
        <h1 class="hh1">Вхід</h1>

        <div class="b-obox-subitem">

          <div class="form-group">
            <label for="idInputOrderEmail" class="text2">E-mail</label><br>
            <input type="text" class="input1" id="idInputOrderEmail" name="phone" placeholder="vpopi4@gmail.com" value="" inputmode="text">
          </div>
        </div>
        <div class="form-group">
          <label for="password" class="text2">Пароль<i>*</i></label><br>
          <input type="text" autocomplete="on" class="input1" id="password" name="password" placeholder="Пароль" value="">
        </div>






        </form>

        <div class="button_reg">
          <button type="submit" class="buttonr_reg">Увійти</button>
        </div>

      </div>
    </div>
  </div>




</main>

app/views/users/new.html.erb
<h1>Реєстрація користувача</h1>

<%= form_with(model: @user, url: users_path) do |form| %>
  <div class="form-group">
    <%= form.label :last_name, 'Прізвище<i></i>'.html_safe %><br>
    <%= form.text_field :last_name, class: 'input1', placeholder: 'Бутко' %>
  </div>

  <div class="form-group">
    <%= form.label :first_name, "Ім'я<i></i>".html_safe %><br>
    <%= form.text_field :first_name, class: 'input1', placeholder: 'Михайло' %>
  </div>

  <div class="form-group">
    <%= form.label :birth_date, 'Дата народження<i></i>'.html_safe %><br>
    <%= form.date_field :birth_date, class: 'input1' %>
  </div>

  <div class="form-group">
    <%= form.label :password, 'Пароль<i></i>'.html_safe %><br>
    <%= form.password_field :password, class: 'input1', placeholder: 'Пароль' %>
  </div>

  <div class="form-group">
    <%= form.label :phone, 'Телефон<i>*</i>'.html_safe %><br>
    <%= form.text_field :phone, class: 'input1', placeholder: '+380660277353', inputmode: 'tel' %>
  </div>

  <div class="form-group">
    <%= form.label :email, 'E-mail' %><br>
    <%= form.text_field :email, class: 'input1', placeholder: 'vpopi4@gmail.com' %>
  </div>

  <div class="button_reg">
    <%= form.submit 'Реєстрація', class: 'buttonr_reg' %>
  </div>
<% end %>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<h1>User</h1>

<p><strong>First Name:</strong> <%= @user.first_name %></p>
<p><strong>Last Name:</strong> <%= @user.last_name %></p>
<p><strong>Phone:</strong> <%= @user.phone %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Birth Date:</strong> <%= @user.birth_date %></p>

<br>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/sign_in.html.erb
<%= render "form_sign_in", user: @user %>

app/views/users/sign_up.html.erb
<%= render "form_sign_up", user: @user %>